### ISSUE TITLE
Review naming of model jar

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-model#5]
Previously, the model jar was named `model-psql.jar`. In the main repo, we've had to workaround the dropping of the suffix. see: https://github.com/openmicroscopy/openmicroscopy/pull/5934/commits/5c9a2f5428534c7e31f19dbd490ea3630a641802

We either need to re-add it or cleanup this assumption.

**Comment by jburel** [comment]
The value is now read from the properties file
See https://github.com/openmicroscopy/openmicroscopy/pull/6011
